### PR TITLE
Average points per event chart

### PR DESCRIPTION
**Pull request by sharmaadvay0**
This pull request creates a chart that shows the average points for a given number of events. This pull request also implements routing. The average chart can be found at /average. The home component can be found at /home. The login component can be found at /. It also fixes a bug where warnings would be treated as errors when creating a production build. It properly displays the name of the app in the tab as well.

### CODE REVIEW

**Comment by sharmaadvay0** [comment]
Here's how it looks:

averageChart

**Review by timstjiang — COMMENTED** [review]
Code looks good. However when I tried to run it on my end it failed to compile. We can address this at the meeting,

**Comment by sharmaadvay0** [comment]
> Code looks good. However when I tried to run it on my end it failed to compile. We can address this at the meeting,

Did you install the new dependencies in the client folder and the root folder? It should compile since it works fine on my end.

**Comment by timstjiang** [comment]
> > Code looks good. However when I tried to run it on my end it failed to compile. We can address this at the meeting,
> 
> Did you install the new dependencies in the client folder and the root folder? It should compile since it works fine on my end.
Ah forgot to run on both, thanks!

**Review by timstjiang — APPROVED** [review]
Looks great, can be merged into main. Will need to integrate it into the page.

**Comment by sharmaadvay0** [comment]
I'll merge it once the login page is done since it depends on the user's token.

**Pull request merged**
